### ISSUE TITLE
填写CSRF和cookie后 然后输入task_id后报错

### ISSUE THREAD

**Issue by Modrm** [QuanQuan-CHO/Bilibili-Genshin-Impact-Live-Grab-Tool#3]
Exception in thread "main" java.lang.IllegalArgumentException: Unexpected char 0xe5 at 497 in Cookie value
        at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
        at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
        at okhttp3.Headers$Builder.add(Headers.kt:261)
        at okhttp3.Request$Builder.addHeader(Request.kt:210)
        at LiveGrabTool.main(LiveGrabTool.java:47)

**Comment by QuanQuan-CHO** [comment]
检查一下你Cookie的497位置是不是一个奇怪的字符

**Comment by liqwang** [comment]
检查一下你Cookie的497位置是不是一个奇怪的字符
https://stackoverflow.com/questions/52287872/how-to-send-special-character-like-%C3%A5-in-header-from-okhttp-library

**Comment by Modrm** [comment]
497位是http的t，
用火狐浏览器重新获取了cookie，可以了，之前是edge的，对比了一下edge获取的cookie长度快到火狐的两倍了。暂时解决问题了。
